-- =====================================================================
-- Migration 001 — Bảng `articles`
-- =====================================================================
-- Ngày: 2026-08-28
-- Mục đích: SRS P12 — schema trước nay tạo tay trên Supabase UI, không có
--           bản ghi lại nào. Người khác clone repo về không dựng lại được
--           môi trường, và không ai biết chính xác schema đang là gì.
--
-- ⚠️ ĐÂY LÀ BẢN DỰNG LẠI TỪ SCHEMA ĐANG CHẠY, không phải migration đã từng
--    được áp dụng. Bảng thật đã tồn tại với 196 bản ghi từ trước.
--    File này để dựng môi trường MỚI từ số không (dev, test, CI).
--    Trên DB đang chạy, `IF NOT EXISTS` khiến nó không làm gì cả — an toàn.
--
-- Cách chạy: Supabase Dashboard → SQL Editor → dán → Run.
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.articles (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       text,
    source      text,
    date        text,          -- Ngày xuất bản DẠNG THÔ do nguồn cung cấp.
                               -- ⚠️ SRS P14: cột này trộn 3 định dạng (ISO,
                               -- RFC 822, 'N/A') nên KHÔNG dùng để lọc/sắp xếp.
                               -- Migration 003 sẽ thêm `published_at date` chuẩn hoá.
    tags        text,          -- Nối bằng ", " chứ không phải mảng Postgres.
    summary     text,          -- Rỗng nghĩa là CHƯA qua AI (SRS P15), không
                               -- phải "AI thấy không có gì để tóm tắt".
    sentiment   text,          -- Lưu bằng value tiếng Việt của enum domain.
    url         text,
    topic       text,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- Cơ chế chống trùng của TOÀN hệ thống nằm ở đây, không nằm trong code.
-- `SupabaseStorageAgent` dùng upsert(on_conflict="url", ignore_duplicates=True)
-- để DB tự quyết định, không cần truy vấn kiểm tra trước.
CREATE UNIQUE INDEX IF NOT EXISTS articles_url_key ON public.articles (url);

-- Phục vụ sắp xếp mặc định của API (FR-01: sort=-created_at).
CREATE INDEX IF NOT EXISTS articles_created_at_idx ON public.articles (created_at DESC);

-- Phục vụ bộ lọc theo chủ đề (FR-01).
CREATE INDEX IF NOT EXISTS articles_topic_idx ON public.articles (topic);

-- Row Level Security — xem ADR 0010. Không tạo policy nào: từ chối tất cả với
-- `anon`/`authenticated`, còn key `sb_secret_` của pipeline bỏ qua RLS.
-- Trên DB đang chạy, lệnh này đã được áp từ 2026-07-10; chạy lại vô hại.
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;
