apiVersion: v1
kind: Service
metadata:
  name: ai-trend-agent-svc
  namespace: ai-trend-agent
  labels:
    app: ai-trend-agent
spec:
  selector:
    app: ai-trend-agent
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
